### ISSUE TITLE
column a.attidentity not found error 25% into connecting to database

### ISSUE THREAD

**Issue by linchelsey** [michaelsogos/pg-diff#1]
After I finished creating my own pg-diff-config.json file, I called 

'pg-diff -c development initial-script'

which began connecting to databases, however, at 25% I get this error:

error: column a.attidentity does not exist

attidentity seems to be a postgres column, not any of the columns that are in the tables in my two databases. Any ideas how to fix the error? I've already double checked to make sure that the username I'm inputting has admin rights to access the database.

**Comment by michaelsogos** [comment]
Dear @linchelsey,

Thanks to using our library. 

which library version are you using?
which pgsql version do you have?

a.attidentity is a column from pgsql 10+ only to know if a specific column is an identity column, but this feature is not available on pg 9.x.

However if you can wait one more day I will publish a newer fixed version.

**Comment by michaelsogos** [comment]
Dear @linchelsey ,

The bug has been fixed, now the library is able to know if the SOURCE and TARGET db version is lower than a specified number (used internally) to keep backward compatibility between 9.x, 10.x and 11.x versions of POSTGRESQL 😄 .

Please update npm package to 1.1.2 !

Please, let me know how it is going, i love to heard about how our libary is considered by the community.

**Comment by linchelsey** [comment]
Hello @michaelsogos,

Thank you for your quick response. I just updated the npm package to 1.1.2 and am running it on psql 10.5. However, after 'pg-diff -c development initial-script', I am now hitting this error at 41%:

```
ReferenceError: sourceViews is not defined
    at Object.__compareProcedures (/usr/local/lib/node_modules/pg-diff-cli/src/compareSchema.js:332:150)
    at Object.compareDatabaseObjects (/usr/local/lib/node_modules/pg-diff-cli/src/compareSchema.js:367:14)
    at __runComparison (/usr/local/lib/node_modules/pg-diff-cli/main.js:283:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

sourceViews isn't one of the fields in the pg-diff-config.json file, so unsure how to proceed - the error seems to be coming from the pg-diff-cli src files.

**Comment by michaelsogos** [comment]
Dear @linchelsey ,

OMG! My unit test didn't test that piece of code.
It was a stupid stuff.

Now you have 1.1.3, thanks for your issue!
