### ISSUE TITLE
PostgresSQL 12.1 ad.adsrc deprecated

### ISSUE THREAD

**Issue by graz-dev** [michaelsogos/pg-diff#17]
Dear @michaelsogos with PostgresSQL 12.1 the **ad.adsrc** is deprecated.
I suggest you to use **pg_get_expr(ad.adbin,ad.adrelid)** instead of it.
Have a nice day.

**Comment by michaelsogos** [comment]
Hi @CastoGraziano ,

Thanks for the tips. You are right.
It will be in next release in few days. Promise.

**Comment by michaelsogos** [comment]
Hi @CastoGraziano ,

This is to inform you that it has been fixed on 1.2.13 version of tool.
