### ISSUE TITLE
Missing semicolon at the end of sequence

### ISSUE THREAD

**Issue by viktorsamokov** [michaelsogos/pg-diff#2]
**VERSION** 
`
pg-diff-cli: 1.2.3
`

**Repro steps**
Created new sequence using postgres:
`CREATE SEQUENCE voucher_code_seq START 1`

Run: 
`pg-diff -c development sequence_name_script`
`pg-diff -m development `

**Observed behavior**
Throws error when executing migration for the next line after the statement for creating sequence
`"error syntax near alter"`

**Desired behavior**
![sequence](https://user-images.githubusercontent.com/9202696/49046244-bca31d00-f1d3-11e8-9078-a2bf182de568.jpg)

**Comment by michaelsogos** [comment]
Resolved from version 1.2.4
