### ISSUE TITLE
dataCompare.enabled : false throws an error that says it's required

### ISSUE THREAD

**Issue by JonathonCwik** [michaelsogos/pg-diff#21]
Replication steps:

1. Set dataCompare.enabled = false
2. Run compare

Expected: Successful
Actual: Failure

Looks like you should be checking for null, not a falsy value.

**Comment by JonathonCwik** [comment]
Fixed in: https://github.com/michaelsogos/pg-diff/pull/25 (pending approval)

**Comment by michaelsogos** [comment]
Hi @SMASH1337 ,

Bug fixed! Thanks for the issue.
