### ISSUE TITLE
compareOptions.schemaCompare.roles is required but not caught in config load

### ISSUE THREAD

**Issue by JonathonCwik** [michaelsogos/pg-diff#22]
Replication Steps:

1. Create a pg-diff-config with a compareOptions.schemaCompare = 
```
"schemaCompare": {
                "namespaces": ["public"],				
                "idempotentScript": true, 
                "dropMissingTable": false, 
                "dropMissingView": false, 
                "dropMissingFunction": false 
},
```

Expected: Fails with an error saying roles is required (or a null check making them not required)
Actual: `TypeError: Cannot read property 'length' of undefined`

**Comment by michaelsogos** [comment]
Hi @SMASH1337,
The v2.x is in early stage, so docs hasn't been updated yet.

I will check this, thanks.

**Comment by michaelsogos** [comment]
Hi @SMASH1337 ,

The docs are udpated and the bug fixed.
**WARNING: Some CLI options are changed**
