### ISSUE TITLE
error: column p.prokind does not exist

### ISSUE THREAD

**Issue by JonathonCwik** [michaelsogos/pg-diff#23]
`error: column p.prokind does not exist`

Sorry, don't have much here, and a little debugging shows that the issue is actually in the pg-diff-api node module but it's through this so I figured I'd make the issue here. I ended up fixing it by removing the `AND p.prokind = 'f'`

**Comment by michaelsogos** [comment]
Hi @SMASH1337,

This is related to #24.
That "f" stand for function and "a" stand for aggregate function and "w" stand for window function. :smile:.
So, probably i missed a Pgsql version specification. 
Can you tell me which pg version you use?

**Comment by JonathonCwik** [comment]
@michaelsogos 9.6.11.

That makes sense, in my pull request in the pg-diff-api, I added a check to ignore aggregate functions rather than using prokind.

**Comment by michaelsogos** [comment]
Hi @SMASH1337 ,

Bug fixed. Thanks for the issue!
