### ISSUE TITLE
Aggregate Functions not supported

### ISSUE THREAD

**Issue by JonathonCwik** [michaelsogos/pg-diff#24]
I have a database with an aggregate function, can you either support Aggregate functions or remove them from being analyzed in the diff by using `AND proisagg is false`  in `CatalogApi.js getFunctions`

**Comment by michaelsogos** [comment]
Hi @SMASH1337, 
Can you tell me which version you use?

**Comment by JonathonCwik** [comment]
@michaelsogos This was all tested on 9.6.11

**Comment by michaelsogos** [comment]
Hi @SMASH1337 ,

The release 2.0.2 bring support for AGGREGATE FUNCTION (excluded ordered-sets)
Let me know 😄 .
