### ISSUE TITLE
Error :No such file or directory.

### ISSUE THREAD

**Issue by lknaubkonrad** [michaelsogos/pg-diff#28]
I've followed the steps in https://michaelsogos.github.io/pg-diff/ but get the following error: 

$ pg-diff -h
  Error: : No such file or directory
$ pg-diff -c development initial-script
  Error: : No such file or directory

Executed from pg-diff-master directory

I've installed node.js successfully.  Node version v6.17.1.  I don't believe this is an issue with Node.js because I can run run node -v, npm -v successfully and write a message back to the terminal window successfully.

node is set in PATH - /usr/bin/node

How do I resolve this issue?

**Comment by michaelsogos** [comment]
Dear @lknaubkonrad  

Seems that you missing the config file, also pg-diff cli must be installed globally. 
When you run pg-diff you must be in same folder where the config file exists.

**Comment by lknaubkonrad** [comment]
$ cd ~/pg-diff-master/
$ sudo npm install -g pg-diff-cli
/usr/bin/pg-diff -> /usr/lib/node_modules/pg-diff-cli/main.js
/usr/lib
└─┬ pg-diff-cli@2.0.4 
  └─┬ pg-diff-api@1.0.8
    └─┬ pg@8.1.0
      └─┬ pg-types@2.2.0
        └── postgres-date@1.0.7 

$ ls -ltr ~/pg-diff-master/*config*
   jsconfig.json
   pg-diff-config.json

$ ls -ltr /usr/lib/node_modules/pg-diff-cli/*config*
   jsconfig.json
   pg-diff-config.json

I've edited the ~/pg-diff-master/pg-diff-config.json and /usr/lib/node_modules/pg-diff-cli/pg-diff-config.json for my environment.

**Comment by michaelsogos** [comment]
Is pg-diff-master a clone of the project?
In that case you don't need to clone, it is supposed to be your internal project, so jsconfig.json should be configured as your needs; any way the tool don't care about that file. 

Moreover, config files under /usr/lib/node_modules... don't have to be changed. 

Once the tool is installed properly on your machine you have to:
1. change pwd directory to your project folder; "cd /root/pg-diff-master"
2. execute the tool; "pg-diff -h"


I notice that you mention node v6.x; I never tested it with a so old version. It has been tested with node v8.x, v10.x, v12.x (v14.x not yet 😄)
