### ISSUE TITLE
error: type "regrole" does not exist

### ISSUE THREAD

**Issue by CamiloEspinosaVera** [michaelsogos/pg-diff#34]
Help!!

**Comment by michaelsogos** [comment]
Dear @CamiloEspinosaVera 

Sorry for the late!!!

Can you give me more detail?
The tool is used by my company and many other around the world with very few issues 😄 .

From the title i suspect an incompatibility with PGSQL version you are using.
I need to know:
1. Which version of pg-diff are you using?
2. Are you using CLI or API library?
3. Which PGSQL version you use?
4. Do you agree to supply me a backup for both SOURCE and TARGET db in the same state you wanna compare but without data?
5. Do you have special extension installed on PGSQL (like POSTGIS, PG_CRYPTO, etc.)?

CLI and API are well tested form 9.6 to 13.

**Comment by michaelsogos** [comment]
Dear @CamiloEspinosaVera 

Did you try latest version?
