### ISSUE TITLE
Feature request: Remove the need for the 'namespaces' field in the config

### ISSUE THREAD

**Issue by codemonstur** [michaelsogos/pg-diff#38]
I would prefer that the tool simply compares all schema's it finds in the databases. Right now, if I create a new schema and forget to add it in my migration config the migration script will be wrong.

**Comment by michaelsogos** [comment]
Dear @codemonstur 

I agree, i will let the array to be empty in order to collect all schema listed on specified source db.
Get in touch! 😄

**Comment by michaelsogos** [comment]
Dear @codemonstur 

Release v2.2.0, look at docs please.
Do you like to test it?

**Comment by codemonstur** [comment]
Tested it. Works great!
