### ISSUE TITLE
Feature Request: Compare comments 

### ISSUE THREAD

**Issue by AstrOsu** [michaelsogos/pg-diff#40]
Hello, 

The comments in our database are mission critical.  Tables, schema, columns, constraints, and views all have comments that I need to compare and create a diff for.  Can this functionality be added to pg-diff?  

The goal is to add 'COMMENT ON' lines in the generated patch file that will add, set to null, and/or update comments on targetClient so that it matches up with the comments on sourceClient.

Thank you for your time

**Comment by michaelsogos** [comment]
Dear @AstrOsu,

Yes, of course. Give me few days and it should be ready.

**Comment by michaelsogos** [comment]
Dear @AstrOsu 

It has been released on v2.3.1.

Can you give it a try and let me know in case of issues?

From my unit tests i discovered a lot of errors _#!@^_, not related to your request but discovered thanks to it.
So, in this new version there are more changes (look at the end of the docs for details) that can impact final quality.

**Comment by AstrOsu** [comment]
@michaelsogos Thanks for the quick work!  Unfortunately it doesn't seem to generate a diff script between two databases with identical schema and data, but differing comments.  Is there a new config file setting?  Or maybe I need to create schema differences in order for the comment differences to be detected?

Confirmed that I'm on commit 0bff1c27f0 "Finished 2.3.1"

**Comment by AstrOsu** [comment]
Wait nevermind!  I forgot to install the latest pg-diff-api, I was reusing my old node_modules.

Michael you are the BEST!  I really appreciate your work here, thank you for saving me so much time and effort and headache.  People like you help people like me succeed, and I wish I could support you in a meaningful way.  Seriously, thank you.

**Comment by michaelsogos** [comment]
@AstrOsu 

You are welcome!
This is the meaning of "open source" 😄 .

Anyway, are you using CLI or API tool ? (of course CLI is dependant on API)
I'm asking because is possible that CLI don't have proper EXACT version of API, and of course if you use CLI then you don't need to install separately API too.

**Comment by AstrOsu** [comment]
I'm using the CLI because I don't need to integrate the pg-diff-api into a project.  My problem was that I forgot to update the pg-diff-api module, but I've confirmed that package.json references the latest tag of the api.

Seems like it's working as intended!
