### ISSUE TITLE
Pg-diff data-compare changes for NULL values doesn't work

### ISSUE THREAD

**Issue by viktorsamokov** [michaelsogos/pg-diff#5]
#### VERSION
pg-diff-cli: 1.2.3

In my development database i had created a table with some columns set as **nullable**, added data and everything worked as it should.

Later i decided to change some of the fields which had a default value of NULL to their appropriate data type, but as soon as i run "pg-diff -c development patch_name" it gave empty patch file. No changes were detected.

For fields that were not NULL from the same table but got altered, the "pg-diff -c development patch_name" worked properly.

Data compare option in pg-diff-config.json is enabled and set properly.

**Comment by michaelsogos** [comment]
Hi Viktor,

I'm not able to replicate the issue.

Can you please share the DDL for source table and target table in order to replicate your issue.

FYI: I tested both cases, when source removed NOT NULL flag, and also the opposite;

**Comment by viktorsamokov** [comment]
> Hi Viktor,
> 
> I'm not able to replicate the issue.
> 
> Can you please share the DDL for source table and target table in order to replicate your issue.
> 
> FYI: I tested both cases, when source removed NOT NULL flag, and also the opposite;

Hi Michael,

Just to be on the same page, not removing the data type of the field, but changing the value (data) of the field from NULL to some value. For example if we have this column with these values:
![image](https://user-images.githubusercontent.com/9202696/50140734-06989380-02a6-11e9-8881-c77f2304968b.png)
But later we change the value of the field to:
![image](https://user-images.githubusercontent.com/9202696/50140818-38115f00-02a6-11e9-9709-aa781bf5ae35.png)

These changes are not detected by the pg-diff.

The DDL sources are as follow:
**SOURCE**:
`CREATE TABLE public.voucher_reasons (
	id_voucher_reason serial NOT NULL,
	default_value float8 NULL,
	"name" varchar(50) NOT NULL,
	id_reason_type int4 NOT NULL,
	id_vat_rate int4 NOT NULL,
	created_on timestamp NOT NULL,
	modified_on timestamp NOT NULL,
	created_by int4 NOT NULL,
	modified_by int4 NOT NULL,
	status_reason int4 NOT NULL,
	status_changed_on timestamp NOT NULL,
	status int4 NOT NULL,
	id_cloud int4 NULL,
	is_reserved bool NOT NULL DEFAULT false,
	default_expiration varchar(50) NULL,
	expiration_readonly bool NOT NULL DEFAULT true,
	barcode_expression varchar(200) NULL,
	CONSTRAINT voucher_reasons_pkey PRIMARY KEY (id_voucher_reason)
)`

**TARGET**:
`CREATE TABLE public.voucher_reasons (
	id_cloud int4 NULL,
	status int4 NOT NULL,
	status_reason int4 NOT NULL,
	modified_by int4 NOT NULL,
	created_by int4 NOT NULL,
	id_vat_rate int4 NOT NULL,
	id_reason_type int4 NOT NULL,
	id_voucher_reason serial NOT NULL,
	default_value float8 NULL,
	"name" varchar(50) NOT NULL,
	status_changed_on timestamp NOT NULL,
	modified_on timestamp NOT NULL,
	created_on timestamp NOT NULL,
	is_reserved bool NOT NULL DEFAULT false,
	default_expiration varchar(50) NULL,
	expiration_readonly bool NOT NULL DEFAULT true,
	barcode_expression varchar(200) NULL,
	CONSTRAINT voucher_reasons_pkey PRIMARY KEY (id_voucher_reason)
)`
