### ISSUE TITLE
Data Compare does not work when tables are not in public schema.

### ISSUE THREAD

**Issue by AdeshShambhu** [michaelsogos/pg-diff#9]
- The data compare functionality breaks when we compare tables which are not in public schema.
- This is due to the function "__collectTableRecords" in retrieveRecords.js, 
- The query : "SELECT MD5(ROW(${config.keyFields.join(',')})::text) AS "rowHash", * FROM ${table}" checks only in public schema by default and "Relation not found" error is generated. Hence schema has to be prefixed to the table in this query.
- possible query for this section is : `SELECT MD5(ROW(${config.keyFields.join(',')})::text) AS "rowHash", * FROM ${config.schema||'public'}.${table}`

**Comment by michaelsogos** [comment]
Thanks for the issue, during this weekend will be resolved.

**Comment by michaelsogos** [comment]
@AdeshShambhu 

Thanks for the suggestion, i totally agree with the solution.
Can you please let me know if it resolve your issue?


It has been release in version 1.2.8
